"""Tests for data handling, model equations, constraints and train/test separation."""
import os, sys
import numpy as np, pandas as pd

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, os.path.join(ROOT, "src"))
import analysis as an, data as dta

class _approx:
    def __init__(self, v, rel=1e-6, abs_tol=0.0): self.v, self.rel, self.abs_tol = v, rel, abs_tol
    def __eq__(self, o): return abs(o-self.v) <= max(self.abs_tol, self.rel*abs(self.v))

from models import OneNodeModel, TwoNodeModel, rollout, one_step


def synth(n=4000, dt=10.0, seed=0):
    """Synthetic two-node system with KNOWN positive parameters.

    Used only to verify the estimator recovers what it should; never as evidence
    about the real hardware.
    """
    rng = np.random.default_rng(seed)
    a_g, b_g, c_g, c_m, b_m, Ta = 2e-4, 2e-3, 8e-4, 1.5e-3, 1e-3, 21.0
    P = 50 + 250 * (rng.random(n) < 0.3) * rng.random(n)
    Tg, Tm = np.zeros(n), np.zeros(n)
    Tg[0], Tm[0] = 30.0, 28.0
    for i in range(n - 1):
        Tg[i+1] = Tg[i] + dt*(a_g*P[i] - b_g*(Tg[i]-Ta) - c_g*(Tg[i]-Tm[i]))
        Tm[i+1] = Tm[i] + dt*(c_m*(Tg[i]-Tm[i]) - b_m*(Tm[i]-Ta))
    d = pd.DataFrame(dict(P=P, Tg=Tg, Tm=Tm))
    d["Tg_next"], d["Tm_next"] = d.Tg.shift(-1), d.Tm.shift(-1)
    d = d.dropna().reset_index(drop=True)
    d["dTg"], d["dTm"] = d.Tg_next - d.Tg, d.Tm_next - d.Tm
    return d, dict(a_g=a_g, b_g=b_g, c_g=c_g, c_m=c_m, b_m=b_m)


def test_two_node_recovers_known_parameters():
    """The estimator is correct: on data generated BY the two-node model it
    recovers the true positive parameters. Any failure on real data is therefore
    a statement about the data, not about the fitting code."""
    d, true = synth()
    m = TwoNodeModel(dt=10.0).fit(d)
    for k, v in true.items():
        assert m.report_.params[k] == _approx(v, 0.05), k
    assert m.report_.admissible


def test_two_node_beats_one_node_on_synthetic_coupled_data():
    """Sanity of the comparison itself: when coupling really exists, the two-node
    model must win. This validates the experiment design."""
    d, _ = synth()
    tr, te = d.iloc[:3000].reset_index(drop=True), d.iloc[3000:].reset_index(drop=True)
    one = OneNodeModel(10.0).fit(tr); two = TwoNodeModel(10.0).fit(tr)
    p1 = rollout(one, te, 30); p2 = rollout(two, te, 30)
    rmse1 = an.metrics(p1[3], p1[1])["RMSE"]; rmse2 = an.metrics(p2[3], p2[1])["RMSE"]
    assert rmse2 < rmse1


def test_physical_constraints_flag_negative_parameters():
    d, _ = synth()
    d = d.copy(); d["dTm"] = -d["dTm"]           # deliberately unphysical
    m = TwoNodeModel(10.0).fit(d)
    assert not m.report_.admissible and m.report_.violations


def test_chronological_split_is_ordered_and_disjoint():
    cfg = dict(split=dict(train_frac=0.6, val_frac=0.15, test_frac=0.25))
    n = 1000
    df = pd.DataFrame(dict(segment_id=np.zeros(n, int),
                           timestamp=pd.date_range("2020-01-01", periods=n, freq="10s"),
                           P=1.0, Tg=1.0, Tm=1.0))
    sp = dta.chronological_split(df, cfg)
    assert sp["train"].timestamp.max() < sp["val"].timestamp.min()
    assert sp["val"].timestamp.max() < sp["test"].timestamp.min()
    assert len(set(sp["train"].timestamp) & set(sp["test"].timestamp)) == 0


def test_rollout_uses_no_future_temperature():
    """Free-running rollout must depend only on the seed temperature and power.
    Corrupting observed temperatures after the seed must not change predictions."""
    d, _ = synth()
    tr, te = d.iloc[:3000].reset_index(drop=True), d.iloc[3000:].reset_index(drop=True)
    two = TwoNodeModel(10.0).fit(tr)
    p_a = rollout(two, te, 30)[1]
    te2 = te.copy()
    mask = np.ones(len(te2), bool); mask[::30] = False       # keep seeds intact
    te2.loc[mask, "Tg"] = 999.0; te2.loc[mask, "Tm"] = 999.0
    p_b = rollout(two, te2, 30)[1]
    assert np.allclose(p_a, p_b)


def test_one_step_predictions_are_finite_and_correct_length():
    d, _ = synth()
    m = OneNodeModel(10.0).fit(d)
    pg, pm, tg, tm = one_step(m, d)
    assert len(pg) == len(d) and np.isfinite(pg).all() and np.isfinite(pm).all()


def test_metrics_handle_nonfinite():
    r = an.metrics(np.array([1.0, 2.0, np.nan]), np.array([1.0, 2.0, 5.0]))
    assert r["n"] == 2 and r["RMSE"] == _approx(0.0, 1e-9, abs_tol=1e-9)


def _run_all():
    import traceback
    fns = [(k, v) for k, v in sorted(globals().items())
           if k.startswith("test_") and callable(v)]
    npass = 0
    for name, fn in fns:
        try:
            fn()
            print("  [PASS] " + name)
            npass += 1
        except Exception as e:
            print("  [FAIL] " + name + ": " + type(e).__name__ + ": " + str(e))
            traceback.print_exc()
    print("")
    print(str(npass) + "/" + str(len(fns)) + " tests passed")
    return 0 if npass == len(fns) else 1


if __name__ == "__main__":
    raise SystemExit(_run_all())
